import { SYNTHESIS_FALLBACK } from './synthesis-fallback';

export const AUTOPILOT_SKILL: string = [
  '---',
  'name: autopilot',
  'description: Run the team pipeline under an automatic gate policy.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '    - "Write(.devin/teams/*.yaml)"',
  '---',
  '',
  'When the user asks to run a pipeline unattended, run the same team pipeline',
  'the `team` skill delegates to:',
  '',
  '    omd team run <team> "<task>"',
  '',
  'autopilot binds the pipeline to an automatic gate policy rather than the',
  'mandatory binary human gates. The concrete auto-approve gate policy is not',
  'yet fixed; until it is, autopilot behaves as the human-gated pipeline. This',
  'skill owns no orchestration of its own.',
  '',
  ...SYNTHESIS_FALLBACK,
  'On activation, run:',
  '',
  '    omd mode set autopilot',
  '',
  'After launching the pipeline, record its run identity in the mode so the',
  'stop gate derives the hold from that run record:',
  '',
  '    omd mode set autopilot --run <run-id>',
  '',
  'Once the criteria are met, run:',
  '',
  '    omd mode clear',
  '',
].join('\n');
