export const DEEP_DIVE_SKILL: string = [
  '---',
  'name: deep-dive',
  'description: Read-only exploration of the codebase (conversational lane).',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '---',
  '',
  'When the user asks to explore or understand code, work read-only in the',
  'conversational lane. deep-dive explores and explains only: it performs no',
  'delegation to the contractual lane and carries no write contract, so it never',
  'enters the validated-artifact path.',
  '',
  'deep-dive carries no persistent mode state and no verification criteria; the',
  'exploration itself stays read-only.',
  '',
].join('\n');
