import type { ModeSkill } from './mode-skill';

const TEAM_SKILL: string = [
  '---',
  'name: team',
  'description: Run a declared team as the fixed architect → executor → reviewer pipeline.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to run a team or a full pipeline on a task, run:',
  '',
  '    omd team run <team> "<task>"',
  '',
  'This launches the fixed three-stage pipeline (architect → executor →',
  'reviewer) with a binary human decision gate between stages. The pipeline owns',
  'orchestration; this skill is only the in-session entry point to it.',
  '',
  'On activation, write `.omd/mode.json` with:',
  '',
  '    { "mode": "team", "context": "team mode active: run the declared team through the fixed three-stage pipeline.", "verification": ["pipeline terminal outcome reported"] }',
  '',
  'Once the criteria are met, clear the state: write `.omd/mode.json` again with',
  'an empty `verification` array.',
  '',
].join('\n');

const RALPH_SKILL: string = [
  '---',
  'name: ralph',
  'description: Delegate a single role to omd run and its validate-repair loop.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to grind a single role to a validated artifact, run:',
  '',
  '    omd run <role> "<task>"',
  '',
  'omd runs the role under its budget and relies on the single validate-repair',
  'attempt to bring the declared artifact into conformance before reporting the',
  'outcome. This skill owns no loop of its own — omd run owns the validate-repair',
  'loop.',
  '',
  'On activation, write `.omd/mode.json` with:',
  '',
  '    { "mode": "ralph", "context": "ralph mode active: grind a single role through omd run and its validate-repair loop.", "verification": ["validate-repair loop reached a valid artifact or a classified failure"] }',
  '',
  'Once the criteria are met, clear the state: write `.omd/mode.json` again with',
  'an empty `verification` array.',
  '',
].join('\n');

const AUTOPILOT_SKILL: string = [
  '---',
  'name: autopilot',
  'description: Run the team pipeline under an automatic gate policy.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to run a pipeline unattended, run the same team pipeline',
  'the `team` skill delegates to:',
  '',
  '    omd team run <team> "<task>"',
  '',
  'autopilot binds the pipeline to an automatic gate policy rather than the',
  'mandatory binary human gates. The concrete auto-approve gate policy is not',
  'yet fixed; until it is, autopilot behaves as the human-gated pipeline. This',
  'skill owns no orchestration of its own.',
  '',
  'On activation, write `.omd/mode.json` with:',
  '',
  '    { "mode": "autopilot", "context": "autopilot mode active: run the team pipeline under the automatic gate policy.", "verification": ["pipeline terminal outcome reported"] }',
  '',
  'Once the criteria are met, clear the state: write `.omd/mode.json` again with',
  'an empty `verification` array.',
  '',
].join('\n');

const PLAN_SKILL: string = [
  '---',
  'name: plan',
  'description: Produce an implementation plan before work begins (support mode).',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks for a plan before implementation, this mode maps to a',
  'planning single-role run that produces a plan artifact:',
  '',
  '    omd run <planning-role> "<task>"',
  '',
  'The concrete omd primitive and lane for `plan` are not yet fixed; the',
  'planning-role correspondence above is recorded as non-normative direction',
  'until the mapping is resolved.',
  '',
  'On activation, write `.omd/mode.json` with:',
  '',
  '    { "mode": "plan", "context": "plan mode active: produce a plan artifact before implementation begins.", "verification": ["plan artifact produced"] }',
  '',
  'Once the criteria are met, clear the state: write `.omd/mode.json` again with',
  'an empty `verification` array.',
  '',
].join('\n');

const VERIFY_SKILL: string = [
  '---',
  'name: verify',
  'description: Check that an artifact conforms to its contract (support mode).',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to confirm an artifact conforms to its contract, this mode',
  'maps to the artifact-validation path that a role run already performs on its',
  'declared output. The concrete omd primitive and lane for `verify` are not yet',
  'fixed; the validation correspondence is recorded as non-normative direction',
  'until the mapping is resolved.',
  '',
  'On activation, write `.omd/mode.json` with:',
  '',
  '    { "mode": "verify", "context": "verify mode active: check the artifact against its contract and record evidence.", "verification": ["verification evidence recorded"] }',
  '',
  'Once the criteria are met, clear the state: write `.omd/mode.json` again with',
  'an empty `verification` array.',
  '',
].join('\n');

const DEEP_DIVE_SKILL: string = [
  '---',
  'name: deep-dive',
  'description: Read-only exploration of the codebase (conversational lane).',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '---',
  '',
  'When the user asks to explore or understand code, work read-only in the',
  'conversational lane. deep-dive explores and explains only: it performs no',
  'delegation to the contractual lane and carries no write contract, so it never',
  'enters the validated-artifact path.',
  '',
  'On activation, write `.omd/mode.json` with:',
  '',
  '    { "mode": "deep-dive", "context": "deep-dive mode active: read-only exploration in the conversational lane.", "verification": [] }',
  '',
  'deep-dive carries no verification criteria — its empty `verification` array',
  'never blocks a stop — and the exploration itself stays read-only.',
  '',
].join('\n');

export const MODE_CATALOG: readonly ModeSkill[] = [
  {
    name: 'autopilot',
    lane: 'contractual',
    delegatesTo: 'pipeline',
    content: AUTOPILOT_SKILL,
  },
  {
    name: 'ralph',
    lane: 'contractual',
    delegatesTo: 'omd-run',
    content: RALPH_SKILL,
  },
  {
    name: 'team',
    lane: 'contractual',
    delegatesTo: 'pipeline',
    content: TEAM_SKILL,
  },
  {
    name: 'plan',
    lane: 'contractual',
    delegatesTo: 'omd-run',
    content: PLAN_SKILL,
  },
  {
    name: 'verify',
    lane: 'contractual',
    delegatesTo: 'omd-run',
    content: VERIFY_SKILL,
  },
  {
    name: 'deep-dive',
    lane: 'conversational',
    delegatesTo: 'none',
    content: DEEP_DIVE_SKILL,
  },
];
