export const PLAN_SKILL: string = [
  '---',
  'name: plan',
  'description: Produce an implementation plan before work begins (support mode).',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks for a plan before implementation, this mode maps to a',
  'planning single-role run that produces a plan artifact:',
  '',
  '    omd run <planning-role> "<task>"',
  '',
  'The concrete omd primitive and lane for `plan` are not yet fixed; the',
  'planning-role correspondence above is recorded as non-normative direction',
  'until the mapping is resolved.',
  '',
  'On activation, run:',
  '',
  '    omd mode set plan',
  '',
  'Once the criteria are met, run:',
  '',
  '    omd mode clear',
  '',
].join('\n');
