export const RALPH_SKILL: string = [
  '---',
  'name: ralph',
  'description: Delegate a single role to omd run and its validate-repair loop.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to grind a single role to a validated artifact, run:',
  '',
  '    omd run <role> "<task>"',
  '',
  'omd runs the role under its budget and relies on the single validate-repair',
  'attempt to bring the declared artifact into conformance before reporting the',
  'outcome. This skill owns no loop of its own — omd run owns the validate-repair',
  'loop.',
  '',
  'On activation, run:',
  '',
  '    omd mode set ralph',
  '',
  'After launching the run, record its identity in the mode so the stop gate',
  'derives the hold from that run record:',
  '',
  '    omd mode set ralph --run <run-id>',
  '',
  'Once the criteria are met, run:',
  '',
  '    omd mode clear',
  '',
].join('\n');
