export const SYNTHESIS_FALLBACK: readonly string[] = [
  'When the user names no team, launch the installed default team by omitting',
  'the team argument:',
  '',
  '    omd team run "<task>"',
  '',
  '## Synthesizing a team',
  '',
  'When the task needs a composition no existing declaration covers — or no team',
  'declaration exists at all — compose one yourself. Discover the installed',
  'roles first and compose exclusively from what it lists:',
  '',
  '    omd roles list --json',
  '',
  'Write the composition as a new declaration under `.devin/teams/`, its name',
  'a slug derived from the task text, and launch it by name:',
  '',
  '    omd team run <slug> "<task>"',
  '',
  'Hold to these rules when synthesizing:',
  '',
  '- Compose only from the roles `omd roles list --json` reports; never invent a',
  '  role.',
  '- The pipeline executes only the fixed architect → executor → reviewer',
  '  stages, so a synthesized team composes exactly those stages.',
  '- Never name the declaration `default`, and never overwrite an existing',
  '  declaration — choose a fresh name on any collision.',
  '- If the composition needs a role the catalog lacks, stop and report the',
  '  missing role with a suggestion to create it. Never author a role',
  '  definition yourself.',
  '',
  '## Keeping or deleting a synthesized team',
  '',
  'After a pipeline launched on a synthesized declaration reaches its terminal',
  'outcome, offer the user the choice to keep the declaration as a reusable',
  'named team or delete it. The installed `default` team belongs to the',
  'installer and is never offered for deletion.',
  '',
];
