import { SYNTHESIS_FALLBACK } from './synthesis-fallback';

export const TEAM_SKILL: string = [
  '---',
  'name: team',
  'description: Run a declared team as the fixed architect → executor → reviewer pipeline.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '    - "Write(.devin/teams/*.yaml)"',
  '---',
  '',
  'When the user asks to run a team or a full pipeline on a task, run:',
  '',
  '    omd team run <team> "<task>"',
  '',
  'This launches the fixed three-stage pipeline (architect → executor →',
  'reviewer) with a binary human decision gate between stages. The pipeline owns',
  'orchestration; this skill is only the in-session entry point to it.',
  '',
  ...SYNTHESIS_FALLBACK,
  'On activation, run:',
  '',
  '    omd mode set team',
  '',
  'Once the criteria are met, run:',
  '',
  '    omd mode clear',
  '',
].join('\n');
