export const VERIFY_SKILL: string = [
  '---',
  'name: verify',
  'description: Check that an artifact conforms to its contract (support mode).',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to confirm an artifact conforms to its contract, this mode',
  'maps to the artifact-validation path that a role run already performs on its',
  'declared output. The concrete omd primitive and lane for `verify` are not yet',
  'fixed; the validation correspondence is recorded as non-normative direction',
  'until the mapping is resolved.',
  '',
  'On activation, run:',
  '',
  '    omd mode set verify',
  '',
  'Once the criteria are met, run:',
  '',
  '    omd mode clear',
  '',
].join('\n');
