export const ARCHITECT_ROLE_AGENT_MD: string = [
  '---',
  'name: architect',
  'description: Turns the requirements into an implementation approach.',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Write(architecture.json)"',
  'omd-output: architecture.json',
  'omd-schema: .devin/schemas/architecture.schema.json',
  'omd-max-turns: 6',
  'omd-context: isolated',
  '---',
  '',
  'You are the architect. Turn the requirements into an implementation approach',
  'and write it to architecture.json for the executor to build against.',
  '',
].join('\n');
