export const DELEGATION_SKILL: string = [
  '---',
  'name: omd-delegate',
  'description: Delegate a task to a named omd role via the contractual lane.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to delegate work to a named role, act as the correspondent:',
  'launch the run detached, then poll its status and narrate progress in the chat.',
  'Do not attempt the work in the conversational lane when hard enforcement is',
  'requested.',
  '',
  'Launch the run in the detached form and capture the run identity it prints:',
  '',
  '    omd run <role> "<task>" --detach',
  '',
  'The command returns immediately, printing a single run identity. Keep that',
  'identity — it is the handle the status surface resolves.',
  '',
  'Poll the status at a restrained cadence — when the user next writes and at',
  'natural pauses, never in a tight loop:',
  '',
  '    omd status <run-id> --json',
  '',
  'Narrate progress from these snapshots only: the stage or turn counters, the',
  'validation state, the liveness, and the terminal outcome. Never quote or rely',
  "on the role session's own conversation — the snapshot is the only channel, and",
  'it never carries transcript content.',
  '',
  'When a snapshot reports a pending gate, present it: name the awaited boundary',
  'and state that the decision happens outside this session, on the omd decision',
  'channel. Never actuate a gate decision from the conversation — you present the',
  'gate, you do not decide it.',
  '',
].join('\n');
