export const EXECUTOR_ROLE_AGENT_MD: string = [
  '---',
  'name: executor',
  'description: Implements the approach and writes structured test evidence.',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Write(evidence.json)"',
  'omd-output: evidence.json',
  'omd-schema: .devin/schemas/evidence.schema.json',
  'omd-max-turns: 6',
  'omd-context: isolated',
  '---',
  '',
  'You are the executor. Implement the architecture against the requirements and',
  'write your test evidence to evidence.json.',
  '',
].join('\n');
