export const HOOK_SCRIPT: string = [
  '#!/usr/bin/env node',
  "import { execFileSync } from 'node:child_process';",
  "import { readFileSync } from 'node:fs';",
  '',
  "const phase = process.argv[2] ?? '';",
  '',
  'function readModeState() {',
  '  let parsed;',
  '  try {',
  "    parsed = JSON.parse(readFileSync('.omd/mode.json', 'utf8'));",
  '  } catch {',
  '    return null;',
  '  }',
  "  if (typeof parsed !== 'object' || parsed === null) {",
  '    return null;',
  '  }',
  '  const { mode, context, verification } = parsed;',
  "  if (typeof mode !== 'string' || typeof context !== 'string') {",
  '    return null;',
  '  }',
  '  if (!Array.isArray(verification)) {',
  '    return null;',
  '  }',
  "  if (!verification.every((criterion) => typeof criterion === 'string')) {",
  '    return null;',
  '  }',
  '  return { mode, context, verification };',
  '}',
  '',
  'function stopDecision(state) {',
  '  if (state !== null && state.verification.length > 0) {',
  '    const reason =',
  "      'Unmet verification criteria for mode ' +",
  '      state.mode +',
  "      ': ' +",
  "      state.verification.join('; ');",
  "    return { decision: 'block', reason, hookSpecificOutput: { decision: 'block', reason } };",
  '  }',
  "  return { decision: 'approve', hookSpecificOutput: { decision: 'approve' } };",
  '}',
  '',
  'function readRunListing() {',
  '  let parsed;',
  '  try {',
  "    parsed = JSON.parse(execFileSync('omd', ['status', '--json'], {",
  "      encoding: 'utf8',",
  "      stdio: ['ignore', 'pipe', 'ignore'],",
  '      timeout: 1500,',
  '    }));',
  '  } catch {',
  '    return [];',
  '  }',
  "  if (typeof parsed !== 'object' || parsed === null) {",
  '    return [];',
  '  }',
  '  if (!Array.isArray(parsed.runs)) {',
  '    return [];',
  '  }',
  '  return parsed.runs.filter(',
  '    (run) =>',
  "      typeof run === 'object' &&",
  '      run !== null &&',
  "      typeof run.runId === 'string' &&",
  "      typeof run.state === 'string',",
  '  );',
  '}',
  '',
  'function ambientSummary() {',
  '  const runs = readRunListing();',
  '  if (runs.length === 0) {',
  "    return '';",
  '  }',
  '  const lines = runs.map((run) => {',
  '    const gate =',
  "      typeof run.pendingGate === 'string' && run.pendingGate !== ''",
  "        ? ' gate ' + run.pendingGate",
  "        : '';",
  '    const since =',
  "      typeof run.stateEnteredAt === 'number'",
  "        ? ' since ' + run.stateEnteredAt",
  "        : '';",
  "    return '- ' + run.runId + ' ' + run.state + gate + since;",
  '  });',
  "  return '\\n\\nProject runs (omd status):\\n' + lines.join('\\n');",
  '}',
  '',
  'function contextInjection(state) {',
  '  const ambient = ambientSummary();',
  "  if (state !== null && state.mode !== '') {",
  "    const additionalContext = 'Active mode: ' + state.mode + '. ' + state.context + ambient;",
  '    return { hookSpecificOutput: { additionalContext } };',
  '  }',
  "  return { hookSpecificOutput: { additionalContext: 'Oh My Devin layer active.' + ambient } };",
  '}',
  '',
  "let raw = '';",
  "process.stdin.on('data', (chunk) => { raw += chunk; });",
  "process.stdin.on('end', () => {",
  '  const state = readModeState();',
  "  const output = phase === 'stop' ? stopDecision(state) : contextInjection(state);",
  '  process.stdout.write(JSON.stringify(output));',
  '});',
  '',
].join('\n');
