export const HOOK_SCRIPT: string = [
  '#!/usr/bin/env node',
  "import { readFileSync } from 'node:fs';",
  '',
  "const phase = process.argv[2] ?? '';",
  '',
  'function readModeState() {',
  '  let parsed;',
  '  try {',
  "    parsed = JSON.parse(readFileSync('.omd/mode.json', 'utf8'));",
  '  } catch {',
  '    return null;',
  '  }',
  "  if (typeof parsed !== 'object' || parsed === null) {",
  '    return null;',
  '  }',
  '  const { mode, context, verification } = parsed;',
  "  if (typeof mode !== 'string' || typeof context !== 'string') {",
  '    return null;',
  '  }',
  '  if (!Array.isArray(verification)) {',
  '    return null;',
  '  }',
  "  if (!verification.every((criterion) => typeof criterion === 'string')) {",
  '    return null;',
  '  }',
  '  return { mode, context, verification };',
  '}',
  '',
  'function stopDecision(state) {',
  '  if (state !== null && state.verification.length > 0) {',
  '    const reason =',
  "      'Unmet verification criteria for mode ' +",
  '      state.mode +',
  "      ': ' +",
  "      state.verification.join('; ');",
  "    return { decision: 'block', reason, hookSpecificOutput: { decision: 'block', reason } };",
  '  }',
  "  return { decision: 'approve', hookSpecificOutput: { decision: 'approve' } };",
  '}',
  '',
  'function contextInjection(state) {',
  "  if (state !== null && state.mode !== '') {",
  "    const additionalContext = 'Active mode: ' + state.mode + '. ' + state.context;",
  '    return { hookSpecificOutput: { additionalContext } };',
  '  }',
  "  return { hookSpecificOutput: { additionalContext: 'Oh My Devin layer active.' } };",
  '}',
  '',
  "let raw = '';",
  "process.stdin.on('data', (chunk) => { raw += chunk; });",
  "process.stdin.on('end', () => {",
  '  const state = readModeState();',
  "  const output = phase === 'stop' ? stopDecision(state) : contextInjection(state);",
  '  process.stdout.write(JSON.stringify(output));',
  '});',
  '',
].join('\n');
