import { STOP_PHASE } from './stop-phase';
import { TOOL_USE_PHASE } from './tool-use-phase';

export const HOOK_SCRIPT: string = [
  '#!/usr/bin/env node',
  "import { execFileSync } from 'node:child_process';",
  '',
  "const phase = process.argv[2] ?? '';",
  '',
  'function fallback() {',
  `  if (phase === '${TOOL_USE_PHASE}') {`,
  '    return {};',
  '  }',
  `  if (phase === '${STOP_PHASE}') {`,
  "    return { decision: 'approve', hookSpecificOutput: { decision: 'approve' } };",
  '  }',
  "  return { hookSpecificOutput: { additionalContext: 'Oh My Devin layer active.' } };",
  '}',
  '',
  'function pipe(raw) {',
  '  let answered;',
  '  try {',
  "    answered = execFileSync('omd', ['hook', phase], {",
  "      encoding: 'utf8',",
  '      input: raw,',
  "      stdio: ['pipe', 'pipe', 'ignore'],",
  '      timeout: 5000,',
  '    });',
  '  } catch {',
  '    return fallback();',
  '  }',
  '  let parsed;',
  '  try {',
  '    parsed = JSON.parse(answered);',
  '  } catch {',
  '    return fallback();',
  '  }',
  "  if (typeof parsed !== 'object' || parsed === null) {",
  '    return fallback();',
  '  }',
  '  return parsed;',
  '}',
  '',
  "let raw = '';",
  "process.stdin.on('data', (chunk) => { raw += chunk; });",
  "process.stdin.on('end', () => {",
  '  process.stdout.write(JSON.stringify(pipe(raw)));',
  '});',
  '',
].join('\n');
