export const REVIEWER_ROLE_AGENT_MD: string = [
  '---',
  'name: reviewer',
  'description: Reviews a diff and writes a structured verdict.',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Write(review.json)"',
  'omd-output: review.json',
  'omd-schema: .devin/schemas/review.schema.json',
  'omd-max-turns: 6',
  'omd-context: isolated',
  '---',
  '',
  'You are the reviewer. Assess the diff against the requirements and write',
  'your verdict to review.json.',
  '',
].join('\n');
