export const RULES_BODY: readonly string[] = [
  '',
  '- **Conversational lane** — roles run as native Devin subagents under soft',
  '  enforcement plus CLI-enforced tool contracts.',
  '- **Contractual lane** — entered when the delegation skill invokes',
  '  `omd run <role> "<task>"` for work needing a validated artifact, budgets,',
  '  and failure semantics.',
  '',
  '## Installed roles',
  '',
  '- `architect` — turns the requirements into an approach and writes a',
  '  structured `architecture.json`.',
  '- `executor` — implements the approach and writes a structured `evidence.json`.',
  '- `reviewer` — assesses a diff and writes a structured `review.json`.',
  '- `critic` — judges a plan or work product, naming what is missing as well',
  '  as what is wrong, and writes a structured `critique.json`.',
  '- `analyst` — turns decided scope into pass/fail acceptance criteria and',
  '  writes a structured `requirements-analysis.json`.',
  '- `security-reviewer` — reports reachable vulnerabilities and writes a',
  '  structured `security-review.json`.',
  '- `debugger` — diagnoses a failure from evidence it produced and writes a',
  '  structured `diagnosis.json`.',
  '- `explore` — maps the files and relationships that answer a question and',
  '  writes a structured `findings-map.json`.',
  '- `document-specialist` — answers from designated documentation, naming',
  '  every source, and writes a structured `research-brief.json`.',
  '',
  '## Delegation',
  '',
  'Ask to delegate work to a named role and the `omd-delegate` skill runs',
  '`omd run` for you.',
  '',
  '## Ambient run status',
  '',
  'Each session start and each prompt carry a summary of the project’s runs.',
  'Surface an entry only when it is attention-worthy: a pending gate, a',
  'stalled run, or a terminal outcome this conversation has not acknowledged',
  'yet. Stay silent about unremarkable progress — a run that is simply',
  'advancing needs no mention.',
  '',
];
