export const RULES_FILE: string = [
  '# Oh My Devin — in-session layer',
  '',
  'This project runs under the Oh My Devin organizational layer. It has two lanes:',
  '',
  '- **Conversational lane** — roles run as native Devin subagents under soft',
  '  enforcement plus CLI-enforced tool contracts.',
  '- **Contractual lane** — entered when the delegation skill invokes',
  '  `omd run <role> "<task>"` for work needing a validated artifact, budgets,',
  '  and failure semantics.',
  '',
  '## Installed roles',
  '',
  '- `reviewer` — assesses a diff and writes a structured `review.json`.',
  '',
  '## Delegation',
  '',
  'Ask to delegate work to a named role and the `omd-delegate` skill runs',
  '`omd run` for you.',
  '',
].join('\n');

export const EXAMPLE_ROLE_AGENT_MD: string = [
  '---',
  'name: reviewer',
  'description: Reviews a diff and writes a structured verdict.',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Write(review.json)"',
  'omd-output: review.json',
  'omd-schema: .devin/schemas/review.schema.json',
  'omd-max-turns: 6',
  'omd-context: isolated',
  '---',
  '',
  'You are the reviewer. Assess the diff against the requirements and write',
  'your verdict to review.json.',
  '',
].join('\n');

export const EXAMPLE_ROLE_SCHEMA: string = `${JSON.stringify(
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    required: ['verdict'],
    properties: {
      verdict: { type: 'string', enum: ['approve', 'request_changes'] },
      notes: { type: 'string' },
    },
    additionalProperties: false,
  },
  null,
  2,
)}\n`;

export const DELEGATION_SKILL: string = [
  '---',
  'name: omd-delegate',
  'description: Delegate a task to a named omd role via the contractual lane.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to delegate work to a named role, run:',
  '',
  '    omd run <role> "<task>"',
  '',
  'This enters the contractual lane: the role produces a validated artifact under',
  'its budget, and omd reports the outcome. Do not attempt the work in the',
  'conversational lane when hard enforcement is requested.',
  '',
].join('\n');

export const HOOKS_MAP: string = `${JSON.stringify(
  {
    SessionStart: [
      {
        hooks: [
          {
            type: 'command',
            command: 'node .devin/hooks/omd-mode.mjs session-start',
          },
        ],
      },
    ],
    UserPromptSubmit: [
      {
        hooks: [
          {
            type: 'command',
            command: 'node .devin/hooks/omd-mode.mjs user-prompt',
          },
        ],
      },
    ],
    Stop: [
      {
        hooks: [
          { type: 'command', command: 'node .devin/hooks/omd-mode.mjs stop' },
        ],
      },
    ],
  },
  null,
  2,
)}\n`;

export const HOOK_SCRIPT: string = [
  '#!/usr/bin/env node',
  "import { readFileSync } from 'node:fs';",
  '',
  "const phase = process.argv[2] ?? '';",
  '',
  'function readModeState() {',
  '  let parsed;',
  '  try {',
  "    parsed = JSON.parse(readFileSync('.omd/mode.json', 'utf8'));",
  '  } catch {',
  '    return null;',
  '  }',
  "  if (typeof parsed !== 'object' || parsed === null) {",
  '    return null;',
  '  }',
  '  const { mode, context, verification } = parsed;',
  "  if (typeof mode !== 'string' || typeof context !== 'string') {",
  '    return null;',
  '  }',
  '  if (!Array.isArray(verification)) {',
  '    return null;',
  '  }',
  "  if (!verification.every((criterion) => typeof criterion === 'string')) {",
  '    return null;',
  '  }',
  '  return { mode, context, verification };',
  '}',
  '',
  'function stopDecision(state) {',
  '  if (state !== null && state.verification.length > 0) {',
  '    const reason =',
  "      'Unmet verification criteria for mode ' +",
  '      state.mode +',
  "      ': ' +",
  "      state.verification.join('; ');",
  "    return { decision: 'block', reason, hookSpecificOutput: { decision: 'block', reason } };",
  '  }',
  "  return { decision: 'approve', hookSpecificOutput: { decision: 'approve' } };",
  '}',
  '',
  'function contextInjection(state) {',
  "  if (state !== null && state.mode !== '') {",
  "    const additionalContext = 'Active mode: ' + state.mode + '. ' + state.context;",
  '    return { hookSpecificOutput: { additionalContext } };',
  '  }',
  "  return { hookSpecificOutput: { additionalContext: 'Oh My Devin layer active.' } };",
  '}',
  '',
  "let raw = '';",
  "process.stdin.on('data', (chunk) => { raw += chunk; });",
  "process.stdin.on('end', () => {",
  '  const state = readModeState();',
  "  const output = phase === 'stop' ? stopDecision(state) : contextInjection(state);",
  '  process.stdout.write(JSON.stringify(output));',
  '});',
  '',
].join('\n');
