export const RULES_FILE: string = [
  '# Oh My Devin — in-session layer',
  '',
  'This project runs under the Oh My Devin organizational layer. It has two lanes:',
  '',
  '- **Conversational lane** — roles run as native Devin subagents under soft',
  '  enforcement plus CLI-enforced tool contracts.',
  '- **Contractual lane** — entered when the delegation skill invokes',
  '  `omd run <role> "<task>"` for work needing a validated artifact, budgets,',
  '  and failure semantics.',
  '',
  '## Installed roles',
  '',
  '- `reviewer` — assesses a diff and writes a structured `review.json`.',
  '',
  '## Delegation',
  '',
  'Ask to delegate work to a named role and the `omd-delegate` skill runs',
  '`omd run` for you.',
  '',
].join('\n');

export const EXAMPLE_ROLE_AGENT_MD: string = [
  '---',
  'name: reviewer',
  'description: Reviews a diff and writes a structured verdict.',
  'allowed-tools:',
  '  - read',
  '  - grep',
  '  - create',
  '  - edit',
  'permissions:',
  '  allow:',
  '    - "Write(review.json)"',
  'omd-output: review.json',
  'omd-schema: .devin/schemas/review.schema.json',
  'omd-max-turns: 6',
  'omd-context: isolated',
  '---',
  '',
  'You are the reviewer. Assess the diff against the requirements and write',
  'your verdict to review.json.',
  '',
].join('\n');

export const EXAMPLE_ROLE_SCHEMA: string = `${JSON.stringify(
  {
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    required: ['verdict'],
    properties: {
      verdict: { type: 'string', enum: ['approve', 'request_changes'] },
      notes: { type: 'string' },
    },
    additionalProperties: false,
  },
  null,
  2,
)}\n`;

export const DELEGATION_SKILL: string = [
  '---',
  'name: omd-delegate',
  'description: Delegate a task to a named omd role via the contractual lane.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '---',
  '',
  'When the user asks to delegate work to a named role, act as the correspondent:',
  'launch the run detached, then poll its status and narrate progress in the chat.',
  'Do not attempt the work in the conversational lane when hard enforcement is',
  'requested.',
  '',
  'Launch the run in the detached form and capture the run identity it prints:',
  '',
  '    omd run <role> "<task>" --detach',
  '',
  'The command returns immediately, printing a single run identity. Keep that',
  'identity — it is the handle the status surface resolves.',
  '',
  'Poll the status at a restrained cadence — when the user next writes and at',
  'natural pauses, never in a tight loop:',
  '',
  '    omd status <run-id> --json',
  '',
  'Narrate progress from these snapshots only: the stage or turn counters, the',
  'validation state, the liveness, and the terminal outcome. Never quote or rely',
  "on the role session's own conversation — the snapshot is the only channel, and",
  'it never carries transcript content.',
  '',
  'When a snapshot reports a pending gate, present it: name the awaited boundary',
  'and state that the decision happens outside this session, on the omd decision',
  'channel. Never actuate a gate decision from the conversation — you present the',
  'gate, you do not decide it.',
  '',
].join('\n');

export const INSTALL_SKILL: string = [
  '---',
  'name: omd-install',
  'description: Validate an omd installation from a Devin session, or perform one when omd is absent.',
  'triggers:',
  '  - model',
  'allowed-tools:',
  '  - exec',
  'permissions:',
  '  allow:',
  '    - "Exec(omd)"',
  '    - "Exec(curl)"',
  '    - "Exec(sh)"',
  '---',
  '',
  'When the user asks to confirm or set up their omd installation, key on the',
  '`omd` binary rather than on how it was installed. omd may have arrived under',
  'either package name — `oh-my-devin` or `ohmydevin` — with any mainstream',
  'package manager, or through the inline installer; treat them the same.',
  '',
  'When omd is available, report its installed version:',
  '',
  '    omd --version',
  '',
  'and report the environment checks, which omd doctor owns:',
  '',
  '    omd doctor',
  '',
  'When omd is not available, perform the installation with the inline installer',
  '(it provisions a Node runtime if none is present), then re-validate:',
  '',
  '    curl -fsSL https://raw.githubusercontent.com/adrianmjim/oh-my-devin/main/install.sh | sh',
  '',
  'After it finishes, run the version check again to confirm the install and',
  'report the resulting version.',
  '',
  'In both cases, present `omd setup` to the user as their next step — it installs',
  'the in-session layer into a project — but do not run it: where the layer goes',
  "is the user's call, made per project.",
  '',
].join('\n');

export const HOOKS_MAP: string = `${JSON.stringify(
  {
    SessionStart: [
      {
        hooks: [
          {
            type: 'command',
            command: 'node .devin/hooks/omd-mode.mjs session-start',
          },
        ],
      },
    ],
    UserPromptSubmit: [
      {
        hooks: [
          {
            type: 'command',
            command: 'node .devin/hooks/omd-mode.mjs user-prompt',
          },
        ],
      },
    ],
    Stop: [
      {
        hooks: [
          { type: 'command', command: 'node .devin/hooks/omd-mode.mjs stop' },
        ],
      },
    ],
  },
  null,
  2,
)}\n`;

export const HOOK_SCRIPT: string = [
  '#!/usr/bin/env node',
  "import { readFileSync } from 'node:fs';",
  '',
  "const phase = process.argv[2] ?? '';",
  '',
  'function readModeState() {',
  '  let parsed;',
  '  try {',
  "    parsed = JSON.parse(readFileSync('.omd/mode.json', 'utf8'));",
  '  } catch {',
  '    return null;',
  '  }',
  "  if (typeof parsed !== 'object' || parsed === null) {",
  '    return null;',
  '  }',
  '  const { mode, context, verification } = parsed;',
  "  if (typeof mode !== 'string' || typeof context !== 'string') {",
  '    return null;',
  '  }',
  '  if (!Array.isArray(verification)) {',
  '    return null;',
  '  }',
  "  if (!verification.every((criterion) => typeof criterion === 'string')) {",
  '    return null;',
  '  }',
  '  return { mode, context, verification };',
  '}',
  '',
  'function stopDecision(state) {',
  '  if (state !== null && state.verification.length > 0) {',
  '    const reason =',
  "      'Unmet verification criteria for mode ' +",
  '      state.mode +',
  "      ': ' +",
  "      state.verification.join('; ');",
  "    return { decision: 'block', reason, hookSpecificOutput: { decision: 'block', reason } };",
  '  }',
  "  return { decision: 'approve', hookSpecificOutput: { decision: 'approve' } };",
  '}',
  '',
  'function contextInjection(state) {',
  "  if (state !== null && state.mode !== '') {",
  "    const additionalContext = 'Active mode: ' + state.mode + '. ' + state.context;",
  '    return { hookSpecificOutput: { additionalContext } };',
  '  }',
  "  return { hookSpecificOutput: { additionalContext: 'Oh My Devin layer active.' } };",
  '}',
  '',
  "let raw = '';",
  "process.stdin.on('data', (chunk) => { raw += chunk; });",
  "process.stdin.on('end', () => {",
  '  const state = readModeState();',
  "  const output = phase === 'stop' ? stopDecision(state) : contextInjection(state);",
  '  process.stdout.write(JSON.stringify(output));',
  '});',
  '',
].join('\n');
