import { AGENT_CONFIG_LOG_SUFFIX } from './agent-config-log-suffix';
import { STUB_LOG_ENV } from './stub-log-env';
import { STUB_SCRIPT_ENV } from './stub-script-env';

export const STUB_SOURCE: string = [
  '#!/usr/bin/env node',
  "'use strict';",
  "const { readFileSync, appendFileSync, writeFileSync } = require('node:fs');",
  '',
  `const scriptPath = process.env['${STUB_SCRIPT_ENV}'];`,
  `const logPath = process.env['${STUB_LOG_ENV}'];`,
  'const args = process.argv.slice(2);',
  '',
  'function fail(message) {',
  "  process.stderr.write('devin-stub: ' + message + '\\n');",
  '  process.exit(1);',
  '}',
  '',
  `if (!scriptPath) { fail('${STUB_SCRIPT_ENV} is not set'); }`,
  `if (!logPath) { fail('${STUB_LOG_ENV} is not set'); }`,
  '',
  'let script;',
  'try {',
  "  script = JSON.parse(readFileSync(scriptPath, 'utf8'));",
  '} catch (error) {',
  "  fail('cannot read stub script: ' + String(error));",
  '}',
  '',
  'const turns = Array.isArray(script.turns) ? script.turns : [];',
  'const listResponses = Array.isArray(script.listResponses)',
  '  ? script.listResponses',
  '  : [];',
  'const listResponse =',
  '  script.listResponse === undefined ? null : script.listResponse;',
  '',
  "const isList = args[0] === 'list';",
  '',
  'let priorTurns = 0;',
  'let priorLists = 0;',
  'try {',
  "  const existing = readFileSync(logPath, 'utf8');",
  "  for (const line of existing.split('\\n')) {",
  "    if (line.trim() !== '') {",
  '      const record = JSON.parse(line);',
  "      if (Array.isArray(record.args) && record.args[0] === 'list') {",
  '        priorLists += 1;',
  '      } else {',
  '        priorTurns += 1;',
  '      }',
  '    }',
  '  }',
  '} catch {}',
  '',
  "appendFileSync(logPath, JSON.stringify({ command: 'devin', args }) + '\\n');",
  '',
  "const agentConfigIndex = args.indexOf('--agent-config');",
  'if (agentConfigIndex !== -1 && args[agentConfigIndex + 1]) {',
  '  try {',
  '    appendFileSync(',
  `      logPath + '${AGENT_CONFIG_LOG_SUFFIX}',`,
  "      readFileSync(args[agentConfigIndex + 1], 'utf8') + '\\n',",
  '    );',
  '  } catch {}',
  '}',
  '',
  'const artifactWrites = Array.isArray(script.artifactWrites)',
  '  ? script.artifactWrites',
  '  : [];',
  'if (!isList && artifactWrites.length > 0) {',
  '  const write =',
  '    artifactWrites[Math.min(priorTurns, artifactWrites.length - 1)];',
  '  try {',
  "    writeFileSync(write.path, write.content, 'utf8');",
  '  } catch {}',
  '}',
  '',
  'let response;',
  'if (isList) {',
  '  if (priorLists < listResponses.length) {',
  '    response = listResponses[priorLists];',
  '  } else if (listResponse !== null) {',
  '    response = listResponse;',
  '  } else {',
  "    fail('no listResponse was scripted');",
  '  }',
  '} else if (priorTurns < turns.length) {',
  '  response = turns[priorTurns];',
  '} else {',
  "  fail('no scripted turn response left');",
  '}',
  '',
  "process.stdout.write(typeof response.stdout === 'string' ? response.stdout : '');",
  "process.stderr.write(typeof response.stderr === 'string' ? response.stderr : '');",
  "process.exit(typeof response.exitCode === 'number' ? response.exitCode : 0);",
  '',
].join('\n');
