export type BenchDimension =
  | 'detection'
  | 'false-positive-resistance'
  | 'severity-accuracy'
  | 'verdict-accuracy'
  | 'gap-coverage'
  | 'spurious-step-resistance'
  | 'criteria-satisfaction'
  | 'verification-outcome'
  | 'test-integrity'
  | 'evidence-accuracy'
  | 'missing-element-coverage'
  | 'root-cause-localization'
  | 'file-recall'
  | 'relationship-coverage'
  | 'source-attribution-accuracy';
